name = "RFImpairmentsModels"
uuid = "9896bf05-9493-4e5b-be64-41b6a423b7e2"
authors = ["Robin Gerzaguet <robin.gerzaguet@irisa.fr> and contributors"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DSP = "0.7"
UnPack = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
